#!/usr/bin/env python
# coding: utf-8

# ## 1. Counting missing values
# <p>Sports clothing and athleisure attire is a huge industry, worth approximately <a href="https://www.statista.com/statistics/254489/total-revenue-of-the-global-sports-apparel-market/">$193 billion in 2021</a> with a strong growth forecast over the next decade! </p>
# <p>In this notebook, we play the role of a product analyst for an online sports clothing company. The company is specifically interested in how it can improve revenue. We will dive into product data such as pricing, reviews, descriptions, and ratings, as well as revenue and website traffic, to produce recommendations for its marketing and sales teams.  </p>
# <p>The database provided to us, <code>sports</code>, contains five tables, with <code>product_id</code> being the primary key for all of them: </p>
# <h3 id="info"><code>info</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_name</code></td>
# <td><code>varchar</code></td>
# <td>Name of the product</td>
# </tr>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>description</code></td>
# <td><code>varchar</code></td>
# <td>Description of the product</td>
# </tr>
# </tbody>
# </table>
# <h3 id="finance"><code>finance</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>listing_price</code></td>
# <td><code>float</code></td>
# <td>Listing price for product</td>
# </tr>
# <tr>
# <td><code>sale_price</code></td>
# <td><code>float</code></td>
# <td>Price of the product when on sale</td>
# </tr>
# <tr>
# <td><code>discount</code></td>
# <td><code>float</code></td>
# <td>Discount, as a decimal, applied to the sale price</td>
# </tr>
# <tr>
# <td><code>revenue</code></td>
# <td><code>float</code></td>
# <td>Amount of revenue generated by each product, in US dollars</td>
# </tr>
# </tbody>
# </table>
# <h3 id="reviews"><code>reviews</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_name</code></td>
# <td><code>varchar</code></td>
# <td>Name of the product</td>
# </tr>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>rating</code></td>
# <td><code>float</code></td>
# <td>Product rating, scored from <code>1.0</code> to <code>5.0</code></td>
# </tr>
# <tr>
# <td><code>reviews</code></td>
# <td><code>float</code></td>
# <td>Number of reviews for the product</td>
# </tr>
# </tbody>
# </table>
# <h3 id="traffic"><code>traffic</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>last_visited</code></td>
# <td><code>timestamp</code></td>
# <td>Date and time the product was last viewed on the website</td>
# </tr>
# </tbody>
# </table>
# <h3 id="brands"><code>brands</code></h3>
# <table>
# <thead>
# <tr>
# <th>column</th>
# <th>data type</th>
# <th>description</th>
# </tr>
# </thead>
# <tbody>
# <tr>
# <td><code>product_id</code></td>
# <td><code>varchar</code></td>
# <td>Unique ID for product</td>
# </tr>
# <tr>
# <td><code>brand</code></td>
# <td><code>varchar</code></td>
# <td>Brand of the product</td>
# </tr>
# </tbody>
# </table>
# <p>We will be dealing with missing data as well as numeric, string, and timestamp data types to draw insights about the products in the online store. Let's start by finding out how complete the data is.</p>

# In[355]:


get_ipython().run_cell_magic('sql', '', 'postgresql:///sports\n\nSELECT COUNT(*) AS total_rows,\nCOUNT(description) AS count_description,\nCOUNT(listing_price) AS count_listing_price,\nCOUNT(last_visited) AS count_last_visited\nFROM info\nLEFT JOIN finance\nUSING(product_id)\nLEFT JOIN traffic\nUSING(product_id)')


# In[356]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert "total_rows" in set(last_output_df.columns), \\\n    """Did you alias the count of all products as "total_rows"?"""\n    assert set(last_output_df.columns) == set([\'total_rows\', \'count_description\', \'count_listing_price\',\n           \'count_last_visited\']), \\\n    """Did you select four columns and use the aliases in the instructions?"""\n\ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    """Did you return a single row containing the count of values for each column?"""\n    assert last_output_df.shape[1] == 4, \\\n    """Did you select four columns?"""\n\ndef test_values():\n    assert last_output_df.values.tolist() == [[3179, 3117, 3120, 2928]], \\\n    """Did you correctly calculate the values for each column? Expected different results."""')


# ## 2. Nike vs Adidas pricing
# <p>We can see the database contains 3,179 products in total. Of the columns we previewed, only one &mdash; <code>last_visited</code> &mdash; is missing more than five percent of its values. Now let's turn our attention to pricing. </p>
# <p>How do the price points of Nike and Adidas products differ? Answering this question can help us build a picture of the company's stock range and customer market. We will run a query to produce a distribution of the <code>listing_price</code> and the count for each price, grouped by <code>brand</code>. </p>

# In[357]:


get_ipython().run_cell_magic('sql', '', '\nSELECT brand,\nCAST(listing_price AS INTEGER),\nCOUNT(*)\nFROM brands\nLEFT JOIN finance\nUSING(product_id)\nWHERE listing_price > 0\nGROUP BY brand, listing_price\nORDER BY listing_price DESC')


# In[358]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'count\', \'listing_price\']), \\\n    """Did you select the correct columns and alias the first as "total_rows"?"""\n\ndef test_shape():\n    assert last_output_df.shape[0] == 77, \\\n    """Did you correctly aggregate by brand? Expected the output to contain 77 products."""\n    assert last_output_df.shape[1] == 3, \\\n    """The output should contain three columns: "brand", "listing_price", and "count"?"""\n\ndef test_values():\n    assert last_output_df.iloc[0].values.tolist() == [\'Adidas\', 300, 2], \\\n    """Did you sort the results by "listing_price" in descending order?"""')


# ## 3. Labeling price ranges
# <p>It turns out there are 77 unique prices for the products in our database, which makes the output of our last query quite difficult to analyze. </p>
# <p>Let's build on our previous query by assigning labels to different price ranges, grouping by <code>brand</code> and <code>label</code>. We will also include the total <code>revenue</code> for each price range and <code>brand</code>. </p>

# In[359]:


get_ipython().run_cell_magic('sql', '', "\nSELECT brand, count(*),\nSUM(revenue) AS total_revenue,\nCASE \nWHEN listing_price < 42 THEN 'Budget'\nWHEN listing_price >= 42 AND listing_price <= 74 THEN 'Average'\nWHEN listing_price >= 74 AND listing_price <= 129 THEN 'Expensive'\nWHEN listing_price > 129 THEN 'Elite'\nEND AS price_category\nFROM finance\nLEFT JOIN brands\nUSING(product_id)\nWHERE brand IS NOT NULL\nGROUP BY brand, price_category\nORDER BY total_revenue DESC")


# In[360]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'price_category\', \'count\', \'total_revenue\']), \\\n    """Did you select the correct columns? Expected "brand", "listing_price", "count", and "total_revenue"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 8, \\\n    "Did you group by brand and labels? Expected there to be eight rows."\n    assert last_output_df.shape[1] == 4, \\\n    "Did you select four columns?"\n    \ndef test_values():\n    assert last_output_df[:4].values.tolist() == [[\'Adidas\', 849, 4626980.069999999, \'Expensive\'],\n     [\'Adidas\', 1060, 3233661.060000001, \'Average\'],\n     [\'Adidas\', 307, 3014316.8299999987, \'Elite\'],\n     [\'Adidas\', 359, 651661.1200000002, \'Budget\']], \\\n    "Did you correctly calculate values for Adidas products? Expected something different."\n    assert last_output_df[4:].values.tolist() == [[\'Nike\', 357, 595341.0199999992, \'Budget\'],\n     [\'Nike\', 82, 128475.59000000003, \'Elite\'],\n     [\'Nike\', 90, 71843.15000000004, \'Expensive\'],\n     [\'Nike\', 16, 6623.5, \'Average\']], \\\n    "Did you correctly calculate values for Nike products? Expected something different."')


# ## 4. Average discount by brand
# <p>Interestingly, grouping products by brand and price range allows us to see that Adidas items generate more total revenue regardless of price category! Specifically, <code>"Elite"</code> Adidas products priced \$129 or more typically generate the highest revenue, so the company can potentially increase revenue by shifting their stock to have a larger proportion of these products!</p>
# <p>Note we have been looking at <code>listing_price</code> so far. The <code>listing_price</code> may not be the price that the product is ultimately sold for. To understand <code>revenue</code> better, let's take a look at the <code>discount</code>, which is the percent reduction in the <code>listing_price</code> when the product is actually sold. We would like to know whether there is a difference in the amount of <code>discount</code> offered between brands, as this could be influencing <code>revenue</code>.</p>

# In[361]:


get_ipython().run_cell_magic('sql', '', '\nSELECT brand, AVG(discount) * 100 as average_discount\nFROM finance\nLEFT JOIN brands\nUSING (product_id)\nWHERE brand IS NOT NULL\nGROUP BY brand')


# In[362]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'average_discount\']), \\\n    """Did you select the correct columns? Expected "brand" and "average_discount"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 2, \\\n    "Did you group by brand? Expected two rows, one per brand."\n    assert last_output_df.shape[1] == 2, \\\n    "Did you select two columns?"\n    \ndef test_values():\n    assert last_output_df.iloc[:, 1].values.tolist() == [0.0, 33.452427184465606], \\\n    "Did you correctly calculate the average discount for the two brands?"')


# ## 5. Correlation between revenue and reviews
# <p>Strangely, no <code>discount</code> is offered on Nike products! In comparison, not only do Adidas products generate the most revenue, but these products are also heavily discounted! </p>
# <p>To improve revenue further, the company could try to reduce the amount of discount offered on Adidas products, and monitor sales volume to see if it remains stable. Alternatively, it could try offering a small discount on Nike products. This would reduce average revenue for these products, but may increase revenue overall if there is an increase in the volume of Nike products sold. </p>
# <p>Now explore whether relationships exist between the columns in our database. We will check the strength and direction of a correlation between <code>revenue</code> and <code>reviews</code>. </p>

# In[363]:


get_ipython().run_cell_magic('sql', '', '\nSELECT \nCORR(revenue, reviews) AS review_revenue_corr\nFROM reviews\nLEFT JOIN finance\nUSING (product_id)')


# In[364]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'review_revenue_corr\']), \\\n    """Did you calculate the correlation between reviews and revenue, aliasing as "review_revenue_corr"?"""\n    \ndef test_shape():\n    assert last_output_df.shape == (1, 1), \\\n    "Did you calculate the correlation between reviews and revenue?"\n    \ndef test_values():\n    assert last_output_df.values.tolist() == [[0.6518512283481301]], \\\n    "Did you correctly calculate how reviews correlates with revenue?"')


# ## 6. Ratings and reviews by product description length
# <p>Interestingly, there is a strong positive correlation between <code>revenue</code> and <code>reviews</code>. This means, potentially, if we can get more reviews on the company's website, it may increase sales of those items with a larger number of reviews. </p>
# <p>Perhaps the length of a product's <code>description</code> might influence a product's <code>rating</code> and <code>reviews</code> &mdash; if so, the company can produce content guidelines for listing products on their website and test if this influences <code>revenue</code>. Let's check this out!</p>

# In[365]:


get_ipython().run_cell_magic('sql', '', '\nSELECT TRUNC(LENGTH(description),-2) AS description_length,\nROUND(AVG(CAST(rating AS NUMERIC)),2) AS average_rating\nFROM info\nINNER JOIN reviews\nUSING (product_id)\nWHERE description IS NOT NULL\nGROUP BY description_length\nORDER BY description_length;')


# In[366]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'description_length\', \'average_rating\']), \\\n    """Did you select the correct columns use the aliases "description_length" and "average_rating"?"""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 7, \\\n    """Did you create bins of 100 characters for "description_length"? Expected the output to contain seven rows."""\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    last_output_df = last_output.DataFrame().values.astype("float")\n    assert last_output_df[0].tolist() == [0.0, 1.87], \\\n    """Did you sort the results by "description_length" in ascending order?"""\n    assert last_output_df[-1].tolist() == [600.0, 3.65], \\\n    "Did you correctly calculate the results? Expected a different average rating for the largest description length bin."')


# ## 7. Reviews by month and brand
# <p>Unfortunately, there doesn't appear to be a clear pattern between the length of a product's <code>description</code> and its <code>rating</code>.</p>
# <p>As we know a correlation exists between <code>reviews</code> and <code>revenue</code>, one approach the company could take is to run experiments with different sales processes encouraging more reviews from customers about their purchases, such as by offering a small discount on future purchases. </p>
# <p>Let's take a look at the volume of <code>reviews</code> by month to see if there are any trends or gaps we can look to exploit.</p>

# In[367]:


get_ipython().run_cell_magic('sql', '', "\nSELECT brand, DATE_PART('month',last_visited) AS month,\nCOUNT(reviews) AS num_reviews\nFROM traffic\nLEFT JOIN reviews\nUSING (product_id)\nLEFT JOIN brands\nUSING (product_id)\nWHERE brand IS NOT NULL AND DATE_PART('month',last_visited) IS NOT NULL\nGROUP BY brand, month\nORDER BY brand, month")


# In[368]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'brand\', \'month\', \'num_reviews\']), \\\n    """Did you select the correct columns? Expected "brand", "month", and "num_reviews"."""\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 24, \\\n    "Did you group by brand and month?"\n    assert last_output_df.shape[1] == 3, \\\n    "Did you select three columns?"\n    \ndef test_values():\n    assert last_output_df.iloc[0].values.tolist() == [\'Adidas\', 1.0, 253], \\\n    "Expected the first row to contain the number of reviews for Adidas products in January."\n    assert last_output_df.iloc[-1].values.tolist() == [\'Nike\', 12.0, 35.0], \\\n    "Expected the last row to contain the number of reviews for Nike products in December."\n    assert max(last_output_df["num_reviews"]) == 272, \\\n    "Did you correctly calculate the number of reviews? Expected the largest number of reviews to be 272 for Adidas products in February."')


# ## 8. Footwear product performance
# <p>Looks like product reviews are highest in the first quarter of the calendar year, so there is scope to run experiments aiming to increase the volume of reviews in the other nine months!</p>
# <p>So far, we have been primarily analyzing Adidas vs Nike products. Now, let's switch our attention to the type of products being sold. As there are no labels for product type, we will create a Common Table Expression (CTE) that filters <code>description</code> for keywords, then use the results to find out how much of the company's stock consists of footwear products and the median <code>revenue</code> generated by these items.</p>

# In[369]:


get_ipython().run_cell_magic('sql', '', "\n WITH footwear AS ( \n     SELECT\n     description, revenue\n     FROM info\n     LEFT JOIN finance\n     USING (product_id)\n     WHERE description IS NOT NULL\n )\n    \n    SELECT COUNT(*) AS num_footwear_products,\n    percentile_disc(0.5) WITHIN GROUP (ORDER BY revenue) AS median_footwear_revenue\n    FROM footwear\n    WHERE description ILIKE '%shoe%' OR description ILIKE '%trainer%' OR \n    description ILIKE '%foot%' ")


# In[370]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'num_footwear_products\', \'median_footwear_revenue\']), \\\n    "Did you select the correct columns and use the aliases specified in the instructions?"\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    "Expected the output to contain one row."\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    assert last_output_df.iloc[0,0] == 2700, \\\n    "Did you count the number of footwear products?"\n    assert last_output_df.iloc[0,1] == 3118.36, \\\n    "Did you calculate the median revenue for footwear products?"')


# ## 9. Clothing product performance
# <p>Recall from the first task that we found there are 3,117 products without missing values for <code>description</code>. Of those, 2,700 are footwear products, which accounts for around 85% of the company's stock. They also generate a median revenue of over $3000 dollars!</p>
# <p>This is interesting, but we have no point of reference for whether footwear's <code>median_revenue</code> is good or bad compared to other products. So, for our final task, let's examine how this differs to clothing products. We will re-use <code>footwear</code>, adding a filter afterward to count the number of products and <code>median_revenue</code> of products that are not in <code>footwear</code>.</p>

# In[371]:


get_ipython().run_cell_magic('sql', '', "\nWITH footwear AS\n(\n    SELECT i.description, f.revenue\n    FROM info AS i\n    INNER JOIN finance AS f \n        ON i.product_id = f.product_id\n    WHERE i.description ILIKE '%shoe%'\n        OR i.description ILIKE '%trainer%'\n        OR i.description ILIKE '%foot%'\n        AND i.description IS NOT NULL\n)\n\nSELECT COUNT(i.*) AS num_clothing_products, \n    percentile_disc(0.5) WITHIN GROUP (ORDER BY f.revenue) AS median_clothing_revenue\nFROM info AS i\nINNER JOIN finance AS f on i.product_id = f.product_id\nWHERE i.description NOT IN (SELECT description FROM footwear);")


# In[372]:


get_ipython().run_cell_magic('nose', '', '\nlast_output = _\nlast_output_df = last_output.DataFrame()\n\ndef test_columns():\n    assert set(last_output_df.columns) == set([\'num_clothing_products\', \'median_clothing_revenue\']), \\\n    "Did you select the correct columns and use the aliases specified in the instructions?"\n    \ndef test_shape():\n    assert last_output_df.shape[0] == 1, \\\n    "Expected the output to contain one row."\n    assert last_output_df.shape[1] == 2, \\\n    "Expected the output to contain two columns."\n    \ndef test_values():\n    assert last_output_df.iloc[0,0] == 417, \\\n    "Did you count the number of clothing products? Expected there to be 417 items."\n    assert last_output_df.iloc[0,1] == 503.82, \\\n    "Did you calculate the median revenue for clothing products? Expected it to be $503.82."')

